{% set name = "awesomeversion" %}
{% set version = "25.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/awesomeversion-{{ version }}.tar.gz
  sha256: d64c9f3579d2f60a5aa506a9dd0b38a74ab5f45e04800f943a547c1102280f31

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0.0

test:
  imports:
    - awesomeversion
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ludeeus/awesomeversion
  summary: One version package to rule them all, One version package to find them, One version package to bring them all, and in the darkness bind them.
  license: MIT
  license_file: LICENCE.md

extra:
  recipe-maintainers:
    - jan-janssen
