{% set name = "awesomeversion" %}
{% set version = "22.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/awesomeversion-{{ version }}.tar.gz
  sha256: 2f4190d333e81e10b2a4e156150ddb3596f5f11da67e9d51ba39057aa7a17f7e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - poetry >=1.0.10
    - poetry-core
  run:
    - python >=3.6

test:
  imports:
    - awesomeversion
    - awesomeversion.comparehandlers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ludeeus/awesomeversion
  license: MIT
  license_family: MIT
  license_file: LICENCE.md
  summary: One version package to rule them all, One version package to find them, One version package to bring them all, and in the darkness bind them.
  description: |
    One version package to rule them all, One version package to find
    them, One version package to bring them all, and in the darkness bind
    them. Make anything a version object, and compare against a vast
    section of other version formats.
  doc_url: https://github.com/ludeeus/awesomeversion
  dev_url: https://github.com/ludeeus/awesomeversion

extra:
  recipe-maintainers:
    - jan-janssen
